Repository FEUP-ESOF-2020-21/open-cx-t2g1-2b-2b, pull requests merged in 2020-12, with the labels that each got.

#19 Now users can save conferences
  src/conf_world/assets/conferences.json
  src/conf_world/lib/database.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/marker_model.dart
  src/conf_world/lib/view/filter_conference.dart
  src/conf_world/lib/view/filter_type.dart
  src/conf_world/lib/view/home_page.dart
  src/conf_world/lib/view/navigation.dart
  src/conf_world/lib/view/world_map.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/lib/widgets/conference_icon.dart
  src/conf_world/lib/widgets/my_button.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
Labels: feature

#20 Model, View and Controller
  src/conf_world/lib/controller/database.dart
  src/conf_world/lib/controller/map_conference_controller.dart
  src/conf_world/lib/controller/route_controller.dart
  src/conf_world/lib/controller/saved_conferences_controller.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/marker_model.dart
  src/conf_world/lib/model/screens/filter_page_model.dart
  src/conf_world/lib/model/screens/filter_type_model.dart
  src/conf_world/lib/model/screens/home_page_model.dart
  src/conf_world/lib/model/screens/navigation_model.dart
  src/conf_world/lib/model/screens/saved_conferences_model.dart
  src/conf_world/lib/view/filter_conference.dart
  src/conf_world/lib/view/filter_type.dart
  src/conf_world/lib/view/home_page.dart
  src/conf_world/lib/view/navigation.dart
  src/conf_world/lib/view/saved_conferences.dart
  src/conf_world/lib/view/screens/filter_page.dart
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/home_page.dart
  src/conf_world/lib/view/screens/navigation.dart
  src/conf_world/lib/view/screens/saved_conferences.dart
  src/conf_world/lib/view/screens/world_map.dart
  src/conf_world/lib/view/widgets/button.dart
  src/conf_world/lib/view/widgets/conference_details.dart
  src/conf_world/lib/view/widgets/conference_pinpoint.dart
  src/conf_world/lib/view/widgets/marker_view.dart
  src/conf_world/lib/view/world_map.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/lib/widgets/conference_icon.dart
Labels: improvement

#21 Saved conferences list
  src/conf_world/lib/controller/database.dart
  src/conf_world/lib/controller/map_conference_controller.dart
  src/conf_world/lib/controller/route_controller.dart
  src/conf_world/lib/controller/saved_conferences_controller.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/marker_model.dart
  src/conf_world/lib/model/screens/filter_page_model.dart
  src/conf_world/lib/model/screens/filter_type_model.dart
  src/conf_world/lib/model/screens/home_page_model.dart
  src/conf_world/lib/model/screens/navigation_model.dart
  src/conf_world/lib/model/screens/saved_conferences_model.dart
  src/conf_world/lib/view/filter_conference.dart
  src/conf_world/lib/view/filter_type.dart
  src/conf_world/lib/view/home_page.dart
  src/conf_world/lib/view/navigation.dart
  src/conf_world/lib/view/screens/filter_page.dart
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/home_page.dart
  src/conf_world/lib/view/screens/navigation.dart
  src/conf_world/lib/view/screens/saved_conferences.dart
  src/conf_world/lib/view/screens/world_map.dart
  src/conf_world/lib/view/widgets/button.dart
  src/conf_world/lib/view/widgets/conference_details.dart
  src/conf_world/lib/view/widgets/conference_pinpoint.dart
  src/conf_world/lib/view/widgets/marker_view.dart
  src/conf_world/lib/view/world_map.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/test/widget_test.dart
Labels: feature

#24 Created a basic workflow to run all tests and get the apk
  .github/workflows/flutter.yml
Labels: automation

#25 Sprint 3 documentation update
  README.md
  docs/README.md
  docs/img/Logical_architecture.png
  docs/img/domain-model.png
  docs/img/domain_model.png
  docs/img/logical-architecture.png
  docs/img/physical-architecture.png
  docs/img/physical_architecture.png
  docs/img/user-story-map.png
Labels: Sprint Review, improvement

#27 Fixing a bug on workflow. APK path is right
  .github/workflows/flutter.yml
Labels: bug

#30 Update physical architeture
  docs/README.md
  docs/img/physical-architecture.png
Labels: improvement

#32 Conferences in timespan
  src/conf_world/android/app/src/main/AndroidManifest.xml
  src/conf_world/android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  src/conf_world/assets/conferences.json
  src/conf_world/assets/img/calendar.png
  src/conf_world/assets/img/icon.png
  src/conf_world/ios/Runner.xcodeproj/project.pbxproj
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  src/conf_world/lib/controller/database.dart
  src/conf_world/lib/controller/map_conference_controller.dart
  src/conf_world/lib/controller/route_controller.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/screens/filter_date_model.dart
  src/conf_world/lib/model/screens/filter_page_model.dart
  src/conf_world/lib/model/screens/filter_type_model.dart
  src/conf_world/lib/model/screens/home_page_model.dart
  src/conf_world/lib/model/screens/navigation_model.dart
  src/conf_world/lib/model/screens/saved_conferences_model.dart
  src/conf_world/lib/view/screens/filter_date.dart
  src/conf_world/lib/view/screens/filter_page.dart
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/home_page.dart
  src/conf_world/lib/view/screens/navigation.dart
  src/conf_world/lib/view/screens/saved_conferences.dart
  src/conf_world/lib/view/screens/world_map.dart
  src/conf_world/lib/view/widgets/button.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
Labels: feature

#35 Unit tests gherkin
  .github/workflows/flutter.yml
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/world_map.dart
  src/conf_world/lib/view/widgets/conference_details.dart
  src/conf_world/lib/view/widgets/conference_pinpoint.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
  src/conf_world/report.json
  src/conf_world/test_driver/app.dart
  src/conf_world/test_driver/app_test.dart
  src/conf_world/test_driver/features/conference_details.feature
  src/conf_world/test_driver/features/filter_conference.feature
  src/conf_world/test_driver/features/open_map.feature
  src/conf_world/test_driver/step/conference_details.dart
  src/conf_world/test_driver/step/open_map.dart
  src/conf_world/test_driver/step/save_conference.dart
  src/conf_world/test_driver/step/tap_button.dart
Labels: Unit Tests, feature

#36 Report update
  docs/README.md
  docs/img/logical-architecture.png
Labels: improvement

#38 Minor fixes
  src/conf_world/android/app/src/main/res/mipmap-hdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-mdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xhdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xxhdpi/launcher_icon.png
  src/conf_world/android/app/src/main/res/mipmap-xxxhdpi/launcher_icon.png
  src/conf_world/assets/conferences.json
  src/conf_world/assets/img/icon.png
  src/conf_world/assets/img/logo.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  src/conf_world/ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  src/conf_world/lib/controller/database.dart
  src/conf_world/lib/controller/filter_type_controller.dart
  src/conf_world/lib/controller/map_conference_controller.dart
  src/conf_world/lib/controller/route_controller.dart
  src/conf_world/lib/controller/saved_conferences_controller.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/screens/filter_date_model.dart
  src/conf_world/lib/model/screens/filter_page_model.dart
  src/conf_world/lib/model/screens/filter_type_model.dart
  src/conf_world/lib/model/screens/home_page_model.dart
  src/conf_world/lib/view/screens/filter_date.dart
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/home_page.dart
  src/conf_world/lib/view/screens/navigation.dart
  src/conf_world/lib/view/screens/world_map.dart
  src/conf_world/lib/view/widgets/conference_details.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
  src/conf_world/report.json
  src/conf_world/test_driver/step/conference_details.dart
  src/conf_world/test_driver/step/save_conference.dart
Labels: improvement

#40 Unit tests
  docs/README.md
  docs/img/logical-architecture.png
  src/conf_world/lib/controller/filter_type_controller.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/screens/filter_date_model.dart
  src/conf_world/lib/model/screens/filter_page_model.dart
  src/conf_world/lib/model/screens/filter_type_model.dart
  src/conf_world/lib/model/screens/home_page_model.dart
  src/conf_world/lib/model/screens/navigation_model.dart
  src/conf_world/lib/model/screens/saved_conferences_model.dart
  src/conf_world/lib/view/screens/filter_date.dart
  src/conf_world/lib/view/screens/filter_page.dart
  src/conf_world/lib/view/screens/filter_type.dart
  src/conf_world/lib/view/screens/home_page.dart
  src/conf_world/lib/view/screens/navigation.dart
  src/conf_world/lib/view/screens/saved_conferences.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
  src/conf_world/report.json
  src/conf_world/test/home_page_test.dart
  src/conf_world/test_driver/app_test.dart
  src/conf_world/test_driver/step/filter_conference.dart
Labels: feature

#41 Sprint 4 review
  docs/README.md
Labels: Sprint Review, improvement

#42 Improvements readme
  docs/README.md
  docs/img/mockups/main-menu.png
  docs/img/prototype.gif
Labels: improvement
