Repository FEUP-ESOF-2020-21/open-cx-t2g1-2b-2b, pull requests merged in 2020-11, with the labels that each got.

#3 Fixed floating pinpoints and apk issues
  src/conf_world/android/app/src/main/AndroidManifest.xml
  src/conf_world/lib/ConferenceIcon.dart
  src/conf_world/lib/MapRoute.dart
Labels: bug

#6 Search conferences
  src/conf_world/lib/ConferenceIcon.dart
  src/conf_world/lib/MapRoute.dart
  src/conf_world/lib/database.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/model/marker_model.dart
  src/conf_world/lib/view/filter_conference.dart
  src/conf_world/lib/view/filter_type.dart
  src/conf_world/lib/view/home_page.dart
  src/conf_world/lib/view/navigation.dart
  src/conf_world/lib/view/world_map.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/lib/widgets/conference_icon.dart
  src/conf_world/lib/widgets/my_button.dart
  src/conf_world/test/widget_test.dart
Labels: feature

#9 Conference details
  src/conf_world/lib/database.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/pubspec.lock
  src/conf_world/pubspec.yaml
  src/conf_world/test/widget_test.dart
Labels: feature

#8 Read conferences information from a json file
  src/conf_world/assets/conferences.json
  src/conf_world/lib/database.dart
  src/conf_world/lib/main.dart
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/view/world_map.dart
  src/conf_world/lib/widgets/conference_details.dart
  src/conf_world/pubspec.yaml
Labels: feature

#12 Added the first deadline of conferences
  src/conf_world/assets/conferences.json
  src/conf_world/lib/model/conference_model.dart
  src/conf_world/lib/widgets/conference_details.dart
Labels: bug

#13 Sprint 2 documentation update
  docs/README.md
  docs/img/mockups/conference.png
  docs/img/mockups/error.png
  docs/img/mvc.png
Labels: improvement

#17 Added diagrams to readme
  docs/README.md
  docs/img/Logical_architecture.png
  docs/img/domain_model.png
  docs/img/mvc.png
  docs/img/physical_architecture.png
  docs/img/use-case.png
Labels: improvement
